load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "test",
    srcs = ["SampleTest.java"],
    test_class = "com.example.test.SampleTest",
    deps = [
        "@maven//:junit_junit",
    ],
)